FROM node:16-alpine3.18

ENV NODE_ENV production

WORKDIR /connector/

COPY ./package.json ./
COPY ./yarn.lock ./
COPY ./entrypoint.sh ./
COPY ./src ./src

RUN set -e; adduser -S -u 1111 connector

RUN set -e; apk add --no-cache git; yarn config set --home enableTelemetry 0; chmod 755 /connector/entrypoint.sh; cd /connector/; yarn install;

USER connector

ENTRYPOINT ["/connector/entrypoint.sh"]