FROM node:16-alpine3.18

ENV NODE_ENV production

WORKDIR /connector/

COPY ./package.json ./
COPY ./yarn.lock ./
COPY ./tsconfig.json ./
COPY ./entrypoint.sh ./
COPY ./src ./src

RUN set -e;  addgroup -g 1111 connector; adduser -S -u 1111 -G connector connector

RUN set -e; apk add --no-cache git; yarn config set --home enableTelemetry 0; chmod 755 /connector/entrypoint.sh; cd /connector/; yarn install --frozen-lockfile;

USER connector

ENTRYPOINT ["/connector/entrypoint.sh"]